/*
 * System call permission table for Capsicum, a capability API for UNIX.
 *
 * Copyright (C) 2012 The Chromium OS Authors <chromium-os-dev@chromium.org>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2, as
 * published by the Free Software Foundation.
 *
 * This file is generated by capsicum_table.js. It should not live in the
 * repository in the long term: eventually, capsicum_table.js will be
 * rewritten in Perl, and will be invoked automatically by the build system,
 * and this file will be removed from the repository.
 */

static inline int run_syscall_table(void *call, unsigned long *args)
{

	if (call == (void *)sys_write)
		return require_rights(args[0], CAP_WRITE|CAP_SEEK);

	if (call == (void *)sys_exit)
		return 0;

	if (call == (void *)sys_openat)
		return require_rights(args[0], CAP_READ|CAP_WRITE);

	if (call == (void *)sys_cap_new)
		return 0;

	return -ECAPMODE;
}
