/*
 * Special system call permissions for Capsicum, a capability API for UNIX.
 *
 * Copyright (C) 2012 The Chromium OS Authors <chromium-os-dev@chromium.org>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2, as
 * published by the Free Software Foundation.
 *
 * This file is generated by capsicum_table.js. It should not live in the
 * repository in the long term: eventually, capsicum_table.js will be
 * rewritten in Perl, and will be invoked automatically by the build system,
 * and this file will be removed from the repository.
 */
#include <linux/mman.h>

static int check_mmap(int arch, int call, unsigned long *args)
{
	int prot = args[2];
	int flags = args[3];
	int fd = args[4];

	if (flags & MAP_ANONYMOUS)
		return 0;

	if (flags & ~(MAP_SHARED|MAP_PRIVATE|MAP_32BIT|MAP_FIXED|MAP_HUGETLB
			|MAP_NONBLOCK|MAP_NORESERVE|MAP_POPULATE|MAP_STACK))
		return -ECAPMODE;

	return require_rights(fd, CAP_MMAP)
		?: ((prot & PROT_READ) ? require_rights(fd, CAP_READ) : 0)
		?: ((prot & PROT_WRITE) ? require_rights(fd, CAP_WRITE) : 0)
		?: ((prot & PROT_EXEC) ? require_rights(fd, CAP_MAPEXEC) : 0);
}
