#!/bin/bash
# Part of a Linux implementation of Capsicum, a capability API for UNIX.
#
# Copyright (C) 2012 The Chromium OS Authors <chromium-os-dev@chromium.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2, as
# published by the Free Software Foundation.
cd `dirname $0`

if [ "$1" = "-kgdb" ]; then
    shift
    export GDB="kgdbwait kgdboc=ttyS1"
    export KGDBSERIAL="-serial tcp::4444,server"
    export DEBUGGER_START='gnome-terminal -e "gdb -x gdb_connect ../../../build-native/vmlinux" -t "Kernel GDB"'
else
    export GDB=""
    export KGDBSERIAL=""
    export DEBUGGER_START=true
fi

if [ "$1" = "" ]; then
  echo "You must specify a test command to run on the hosted system (/tests/ maps to test-files/)"
  echo "Usage: $0 <test-command>"

  exit 1
fi

if [ ! -e test-files.img ]; then
    dd if=/dev/zero of=test-files.img bs=1024k count=1024
    mkfs -t ext4 test-files.img
fi

sudo mount -o loop test-files.img mnt/ && sudo rm -rf mnt/* && sudo cp -a test-files/* mnt/ && sudo umount mnt/ &&
($DEBUGGER_START & sudo kvm -m 4096 -vnc :1 -serial stdio $KGDBSERIAL -pidfile /tmp/kvm.pid -hda test.img -hdb test-files.img -kernel ../../../build-native/arch/x86/boot/bzImage -append "root=/dev/sda cwd=\"`pwd`\" runtest=\"$*\" console=ttyS0 security=capsicum test_mount=\"/dev/sdb\" $GDB")
#-virtfs fsdriver,path=`pwd`/test-files,security_model=,readonly,mount_tag=testfiles

#sudo kvm -m 1024 -vga std -pidfile /tmp/kvm.pid -net nic,model=virtio  -net user,hostfwd=tcp::9222-:22 -hda /home/meredydd/trunk/src/build/images/x86-generic/R20-2083.0.2012_04_04_1057-a1/chromiumos_test_image.bin -kernel build/x86-generic/arch/x86/boot/bzImage -append 'quiet console=tty2 init=/sbin/init boot=local rootwait ro noresume noswap loglevel=1 noinitrd dm_verity.error_behavior=2 dm_verity.max_bios=1024 dm_verity.dev_wait=1 root=/dev/dm-0 i915.modeset=1 cros_legacy cros_debug dm="vroot none ro,0 1740800 verity payload=PARTUUID=91362B9E-36D6-A240-8050-122786BD0EBC hashtree=PARTUUID=91362B9E-36D6-A240-8050-122786BD0EBC hashstart=1740800 alg=sha1 root_hexdigest=8029d76d46b28e0ca215e73b530534c3c1b75ae8 salt=468bea4faa12dcf69728f081b080aa8505a7d846b2fd3bb6796fcca61d17231c" kgdbwait kgdboc=ttyS1' -serial "stdio" -serial "pty"
