#!/bin/bash
# Part of a Linux implementation of Capsicum, a capability API for UNIX.
#
# Copyright (C) 2012 The Chromium OS Authors <chromium-os-dev@chromium.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2, as
# published by the Free Software Foundation.
cd `dirname $0`

if [ "$1" = "-v" ]; then
    shift
    export LOUD=true
else
    export LOUD=false
fi

if [ "$1" = "-vm" -o "$1" = "-x86" ];  then
    shift
    export VM=true
else
    export VM=false
fi

if [ "$1" = "-kgdb" ]; then
    shift
    export KGDB=-kgdb
    export TARGETS="bzImage vmlinux"
else
    export TARGETS=bzImage
    export KGDB=""
fi

if [ "$1" = "-a" ]; then
    shift
    export TESTS="kt;kt procdesc;cap_new.test;procdesc.test;seccomp.test;fexecve_syscall.test"
else
    TESTS="$@"
fi

if expr match "$1" ".*\\.test\\|kt" >/dev/null ; then
    make --no-print-directory -C test-files $1 || exit 1
fi

echo "Building..."

if $VM ; then

    make -C ../../../ -j14 $TARGETS O=build-native/ >/dev/null && (./run-vm-test-on-last-build $KGDB $TESTS 2>&1 | sed -n '/---- Executing: .* ----/,$p')

else
    if $LOUD; then

	make -C ../../../ -j 14 linux ARCH=um O=build/ && ./run-test-on-last-build $TESTS

    else

	make -C ../../../ -j 14 linux ARCH=um O=build/ >/dev/null && (./run-test-on-last-build $TESTS 2>&1 | sed -n '/---- Executing: .* ----/,$p' | grep -Pav 'remove_umid_dir - remove_files_and_dir failed with err = -16|System halted.')
    fi
fi

