#!/bin/bash
# Part of a Linux implementation of Capsicum, a capability API for UNIX.
#
# Copyright (C) 2012 The Chromium OS Authors <chromium-os-dev@chromium.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2, as
# published by the Free Software Foundation.
cd `dirname $0`
if [ "$1" = "" ]; then
  echo "You must specify a test command to run on the hosted system (/tests/ maps to test-files/)"
  echo "Usage: $0 <test-command>"

  exit 1
fi
../../../build/linux ubd0=test.img rw con0=fd:2 con1=fd:0,fd:1 con=pts mem=4096M security=capsicum cwd="\"`pwd`\"" runtest="\"$*\""
